name: Shellscript best practices

on:
  workflow_call:
    inputs:
      files:
        required: false
        default: ./*.sh
        type: string

jobs:

  shell-linter:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        name: Checkout source code

      - name: Install shellcheck
        run: |
          sudo apt-get update -qq
          sudo apt-get install shellcheck

      - name: Check files
        run: shellcheck --shell=bash ${{ inputs.files }}
