name: Shellscript best practices

on:
  workflow_call:
    inputs:
      context:
        required: false
        default: .
        type: string
      python_version:
        required: true
        type: string

jobs:

  shell-linter:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        run: |
          sudo apt-get update -qq
          sudo apt-get install shellcheck

      - name: Check files
        run: shellcheck --shell=bash *.sh
