name: Terraform best practices

# I know that I could install the packages here using this workflow,
# but I prefer that each package has this as an explicit dependency
# in a file, named requirements-dev.txt

on:
  workflow_call:
    inputs:
      dir:
        required: false
        default: .
        type: string



      terraform_version:
        required: false
        default: 1.4.6


jobs:

  terrascan:
    name: terrascan-action
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Terrascan
      id: terrascan
      uses: accurics/terrascan-action@main
      with:
        iac_type: 'terraform'
        iac_version: 'v14'
        policy_type: 'aws'
        only_warn: true
        verbose: true
        iac_dir: ${{ inputs.dir }}
        policy_path:
        skip_rules:
        config_path:
        find_vulnerabilities:

  terraform:
    name: "Terraform"
    needs:
      - terrascan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.dir }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.terraform_version }}
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform plan -no-color

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
