# https://docs.docker.com/ci-cd/github-actions/
name: Docker build and push

on:
  workflow_call:
    inputs:
      context:
        required: false
        default: .
        type: string
      file:
        required: false
        default: ./Dockerfile
        type: string
      registry:
        required: true
        default: 'docker.io'  # 'ghcr.io', 'registry.fly.io'
        type: string
      push:
        required: false
        default: true
        type: boolean
      tags:
        required: false
        type: string
    secrets:
      username:
        required: true
      password:
        required: true

jobs:
  login-build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          push: ${{ inputs.push }}
          tags: ${{ inputs.tags }}
