# https://docs.docker.com/ci-cd/github-actions/
name: Docker build and push

on:
  workflow_call:
    inputs:

    # Registry

      context:
        required: false
        default: .
        type: string
      file:
        required: false
        default: ./Dockerfile
        type: string
      registry:
        required: true
        default: 'docker.io'
        # default: 'quay.io'
        # default: 'ghcr.io'
        # default: 'registry.fly.io'
        type: string
      push:
        required: false
        default: true
        type: boolean
      tag:
        required: false
        type: string
      provenance:
        required: false
        default: false
        type: boolean

    # Trivy
      trivy_version:
        required: false
        default: 'v0.18.3'
        type: string
      vuln-type:
        required: false
        default: 'os,library'
        type: string
      severity:
        required: false
        default: 'CRITICAL,HIGH'
        type: string
      format:
        required: false
        default: 'table'
        type: string
      exit-code:
        required: false
        default: '1'
        type: string
      ignore-unfixed:
        required: false
        default: true
        type: boolean
    secrets:

    # Registry
      username:
        required: true
      password:
        required: true

jobs:
  login-build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

#       - name: Build
#         uses: docker/build-push-action@v3
#         with:
#           context: ${{ inputs.context }}
#           file: ${{ inputs.file }}
#           push: false
#           tags: |
#             ${{ inputs.tags_local }}
#             ${{ inputs.tags_remote }}

#           # This flag represents a bug in deployment,
#           # adding it partially solves it, however it
#           # must be checked
#           provenance: ${{ inputs.provenance }}






      - name: Docker buildx
        run: |
          docker buildx build --file ${{ inputs.file }} --provenance '${{ inputs.provenance }}' \
          --tag ${{ inputs.tag }} ${{ inputs.context }}






      - name: Image list
        run: docker image ls












      - name: Image list
        run: curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | \
          sh -s -- -b /usr/local/bin ${{ inputs.trivy_version }}

      - name: Trivy scan
        run: |
          trivy image --severity ${{ inputs.severity }} --vuln-type ${{ inputs.vuln-type }} \
             --exit-code ${{ inputs.exit-code }} --format ${{ inputs.format }} \
             ${{ inputs.tag }}
