# https://docs.docker.com/ci-cd/github-actions/
name: Docker build and push

on:
  workflow_call:
    inputs:

    # Registry

      context:
        required: false
        default: .
        type: string
      file:
        required: false
        default: ./Dockerfile
        type: string
      platforms:
        required: false
        default: "linux/amd64"
        description: 'comma separated list of platforms'
        type: string
      registry:
        required: false
        default: 'docker.io'
        # default: 'quay.io'
        # default: 'ghcr.io'
        # default: 'registry.fly.io'
        type: string
      repo:
        required: false
        type: string
      tag:
        required: false
        type: string
      push:
        required: false
        default: true
        type: boolean
      provenance:
        required: false
        default: false
        description: |
          This flag represents a bug in deployment,
          adding it partially solves it, however it
          must be checked
        type: boolean

    # Trivy

      trivy_version:
        required: false
        default: 'v0.18.3'
        type: string
      vuln-type:
        required: false
        default: 'os,library'
        type: string
      severity:
        required: false
        default: 'CRITICAL,HIGH'
        type: string
      format:
        required: false
        default: 'table'
        type: string
      exit-code:
        required: false
        default: '1'
        type: string
      ignore-unfixed:
        required: false
        default: true
        type: boolean
      skip-files:
        required: false
        default: ''
        description: 'comma separated list of dirs'
        type: string
      skip-dirs:
        required: false
        default: ''
        description: 'comma separated list of files'
        type: string

    secrets:

    # Registry

      username:
        required: false
      password:
        required: false

jobs:
  login-build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Login to registry
        uses: docker/login-action@v2
        if: ${{ inputs.push }}
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build && Push
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          platforms: ${{ inputs.platforms }}
          provenance: ${{ inputs.provenance }}
          push: ${{ inputs.push }}
          tags: ${{ inputs.registry }}/${{ inputs.repo }}:${{ inputs.tag }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        if: ${{ inputs.push }}
        with:
          image-ref: ${{ inputs.registry }}/${{ inputs.repo }}:${{ inputs.tag }}
          format: ${{ inputs.format }}
          exit-code: ${{ inputs.exit-code }}
          ignore-unfixed: ${{ inputs.ignore-unfixed }}
          vuln-type: ${{ inputs.vuln-type }}
          severity: ${{ inputs.severity }}
          skip-files: ${{ inputs.skip-files }}
          skip-dirs: ${{ inputs.skip-dirs }}
