# https://docs.docker.com/ci-cd/github-actions/
name: Docker build and push

on:
  workflow_call:
    inputs:

    # Registry

      context:
        required: false
        default: .
        type: string
      file:
        required: false
        default: ./Dockerfile
        type: string
      registry:
        required: true
        default: 'docker.io'
        # default: 'quay.io'
        # default: 'ghcr.io'
        # default: 'registry.fly.io'
        type: string
      push:
        required: false
        default: true
        type: boolean
      tags:
        required: false
        type: string
      provenance:
        required: false
        default: false
        type: boolean

    # Trivy

      vuln-type:
        required: false
        default: 'os,library'
        type: string
      severity:
        required: false
        default: 'CRITICAL,HIGH'
        type: string
      format:
        required: false
        default: 'table'
        type: string
      exit-code:
        required: false
        default: '1'
        type: string
      ignore-unfixed:
        required: false
        default: true
        type: boolean
    secrets:

    # Registry
      username:
        required: true
      password:
        required: true

jobs:
  login-build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          push: false
          tags: ${{ inputs.tags }}

          # This flag represents a bug in deployment,
          # adding it partially solves it, however it
          # must be checked
          provenance: ${{ inputs.provenance }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ inputs.tags }}
          format: ${{ inputs.format }}
          exit-code: ${{ inputs.exit-code }}
          ignore-unfixed: ${{ inputs.ignore-unfixed }}
          vuln-type: ${{ inputs.vuln-type }}
          severity: ${{ inputs.severity }}

      - name: Push
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          push: ${{ inputs.push }}
          tags: ${{ inputs.tags }}

          # This flag represents a bug in deployment,
          # adding it partially solves it, however it
          # must be checked
          provenance: ${{ inputs.provenance }}
