name: 'Helm: lint and install'

on:
  workflow_call:
    inputs:

      path:
        required: true
        type: string
      name:
        required: true
        type: string
      repo_name:
        required: true
        type: string
      repo_slug:
        required: true
        type: string
      repo_url:
        required: true
        type: string
      version:
        required: false
        default: ''
        type: string
      helm_version:
        required: false
        default: ''
        type: string

jobs:
  lint-install:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.path }}

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Install specific Helm version
        if: inputs.helm_version != ''
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh --version ${{ inputs.helm_version }}

      - run: helm version

      - name: Install yamllint
        run: sudo apt-get install yamllint

      - name: Install yamllint
        run: yamllint -v

      - run: yamllint .

      - name: Adding ${{ inputs.name }} repo
        run: helm repo add ${{ inputs.repo_name }} ${{ inputs.repo_url }}

      - name: Update Helm repos
        run: helm repo update

      - name: Install latest release of ${{ inputs.name }}
        if: inputs.version == ''
        run: helm install ${{ inputs.name }} ${{ inputs.repo_slug }}

      - name: Install ${{ inputs.version }} release of ${{ inputs.name }}
        if: inputs.version != ''
        run: helm install ${{ inputs.name }} ${{ inputs.repo_slug }} --version ${{ inputs.version }}
