name: 'Helm: lint and install'

on:
  workflow_call:
    inputs:

      path:
        required: true
        type: string
      name:
        required: true
        type: string
      repo_name:
        required: true
        type: string
      repo_url:
        required: true
        type: string
      version:
        required: false
        default: ''
        type: string

jobs:
  lint-install:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.path }}

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Install yamllint
        run: sudo apt-get install yamllint

      - run: yamllint .

      - name: Adding ${{ inputs.name }} repo
        run: helm repo add ${{ inputs.repo_name }} ${{ inputs.repo_url }}

      - name: Update Helm repos
        run: helm repo update

      - name: Install latest release of ${{ inputs.name }}
        if: inputs.version == ''
        run: helm install ${{ inputs.name }} ${{ inputs.repo_slug }}

      - name: Install ${{ inputs.version }} release of ${{ inputs.name }}
        if: inputs.version != ''
        run: helm install ${{ inputs.name }} ${{ inputs.repo_slug }} --version ${{ inputs.version }}
