on:
  workflow_call:
    inputs:
      file:
        required: true
        type: string

      os:
        type: string
        required: true
        default: ubuntu-latest

      path:
        required: true
        type: string
        default: .

    secrets:
      TOKEN:
        required: true

jobs:
  lint:
    runs-on: ${{ inputs.os }}
    permissions:
      contents: read

    env:
      PKR_VAR_token: ${ secrets.token }}

    steps:

      - uses: actions/checkout@v3

      - name: Packer init
        uses: hashicorp/packer-github-actions@master
        with:
          command: init
          arguments: "-upgrade"
          target: ${{ inputs.file }}
          working_directory: ${{ inputs.path }}

        env:
          PACKER_LOG: 1

      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: ${{ inputs.file }}
          working_directory: ${{ inputs.path }}

        env:
          PACKER_LOG: 1
