on:
  workflow_call:
    inputs:
      file:
        required: true
        type: string

      os:
        required: true
        type: string
        default: ubuntu-latest

    secrets:
      token:
        required: true

jobs:
  lint:
    runs-on: ${{ inputs.os }}
    permissions:
      contents: read

    env:
      PKR_VAR_token: ${ secrets.token }}

    steps:

      - uses: actions/checkout@v3

      # fix backwards incompatibilities in template
      - name: Fix Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: fix

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: ${{ inputs.file }}
