on:
  workflow_call:
    inputs:
      file:
        required: true
        type: string

      os:
        type: string
        default: ubuntu-latest

    secrets:
      TOKEN:
        required: true

jobs:
  lint:
    runs-on: ${{ inputs.os }}
    permissions:
      contents: read

    steps:

      - uses: actions/checkout@v3

      - run: |
          sudo apt-get update
          sudo apt-get install tree
          tree .

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: ${{ inputs.file }}
        env:
          PACKER_LOG: 1
