name: Python lint
on:
  workflow_call:
    inputs:
      python_version:
        default: '3.10.2'
        required: false
        type: string

jobs:

  linter:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Print the input name to STDOUT
        run: echo The username is ${{ inputs.python_version }}
