name: Terraform best practices

on:
  workflow_call:
    inputs:
      dir:
        required: false
        default: .
        type: string
      organization:
        required: false
        type: string
      workspace:
        required: false
        type: string
      terraform_version:
        required: false
        default: '1.5.4'
        type: string

    secrets:
      tf_api_token:
        required: true

jobs:
  apply:
    runs-on: ubuntu-latest
    env:
      TF_API_TOKEN: ${{ secrets.tf_api_token }}
    defaults:
      run:
        working-directory: ${{ inputs.dir }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.terraform_version }}
    
      - name: Upload Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
        id: plan-upload
        with:
          organization: ${{ inputs.organization }}
          workspace: ${{ inputs.workspace }}
          directory: ${{ inputs.dir }}
          speculative: true

      - name: Create Plan Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.0
        id: plan-run
        with:
          organization: ${{ inputs.organization }}
          workspace: ${{ inputs.workspace }}
          configuration_version: ${{ steps.plan-upload.outputs.configuration_version_id }}
          plan_only: true

      - name: Get Plan Output
        uses: hashicorp/tfc-workflows-github/actions/plan-output@v1.0.0
        id: plan-output
        with:
          plan: ${{ fromJSON(steps.plan-run.outputs.payload).data.relationships.plan.data.id }}

      - name: Summary
        run: |
          echo "#### Terraform Cloud Plan Output
          ```
          Plan: ${{ steps.plan-output.outputs.add }} to add, ${{ steps.plan-output.outputs.change }} to change, ${{ steps.plan-output.outputs.destroy }} to destroy.
          ```
          [Terraform Cloud Plan](${{ steps.plan-run.outputs.run_link }})" >> $GITHUB_STEP_SUMMARY
