name: YAML best practices

on:
  workflow_call:
    inputs:
      dir:
        required: false
        default: .
        type: string

jobs:

  yaml-linter:
    runs-on: ubuntu-latest
    steps:

      - name: Install yamllint
        run: |
          sudo apt-get update -qq
          sudo apt-get install yamllint

      - name: Check files in directory
        run: yamllint ${{ inputs.dir }}
